### ISSUE TITLE
技術選定ってやつが必要らしい

### ISSUE THREAD

**Issue by Sakanaaa-itf** [Sakanaaa-itf/portfolio_site#1]

**Comment by momeemt** [comment]
PureScript + [Jelly](https://jelly.yukikurage.net/)とかどうでしょうか

**Comment by momeemt** [comment]
他の選択肢も提案します。
[C/C++ から WebAssembly へのコンパイル](https://developer.mozilla.org/ja/docs/WebAssembly/C_to_Wasm)

**Comment by Sakanaaa-itf** [comment]
きっとそれで書いてる個人リポジトリがあるんだろうなぁワクワク

**Comment by momeemt** [comment]
昨日ちらっと話したのは、これです → [Cloudflare R2](https://www.cloudflare.com/ja-jp/developer-platform/r2/)

**Comment by Sakanaaa-itf** [comment]
ま、フレームワークはNext.jsで、そのほかは適宜
